### ISSUE TITLE
Extending the fasting time vs. eating fewer calories

### ISSUE THREAD

**Issue by thenickcox** [arielf/weight-loss#14]
In the docs, you mention

> Extending the fasting time was one major accelerator of weight-loss rate.

You also state

> Sleeping longer consistently appeared as the #1 factor in losing weight.…It took me a while to figure out the sleep part. When we sleep we don't eat. It is that simple.…Our sleeping time is our longest daily fasting time.

I was surprised by your conclusion and, after thinking about it, thought, "That makes sense."

After thinking about it some more, I'm curious how you determined longer fasting was a factor in and of itself. There is more than one variable there, it seems. If you skip breakfast, you're not just fasting longer; assuming you ate at roughly the same rate throughout the day on a day you didn't skip breakfast, you're also eating fewer calories. That is, if you normally ate 3 x 800 calorie meals, but then switched to sleeping longer and skipping breakfast, then ate 2 x 800 calorie meals, you're also cutting your calorie consumption by ~33%.

Did you eat an amount of calories equal to what you _would've_ eaten during breakfast throughout the day to be more confident that it was fasting time _alone_ that lead to the weight loss?

If so, that _would_ be both a surprising and valuable insight, and worth mentioning!

**Comment by arielf** [comment]
@thenickcox 
1. You're probably right on all counts :)
2.  The original data-set I played with here, is pretty old (over 3 years) and I simply didn't have the time/chance to redo the research better.  I can't answer your specific answers since I don't really remember these details. I decided to publish something which is very far from perfect, and has multiple issues, in order to share what I learned, encourage questions, and to give others a chance to improve on it.
3. I would have definitely tacked this differently, given a second chance. In particular, I would try to get more accurate data (more accurate calorie count, BMI measurements, more accurate scales, to name a few)
