### ISSUE TITLE
Neat analysis! How many days worth of data did you use?

### ISSUE THREAD

**Issue by dandv** [arielf/weight-loss#23]
Hi, I run the [Quantified Self Forum](https://forum.quantifiedself.com/) and we'd love to learn more about your experiment. [How many days](https://github.com/arielf/weight-loss/blob/master/QandA.md#machine-learning-arent-you-over-fitting-the-data) were in the data-set that led to the [variable-importance chart](https://github.com/arielf/weight-loss#and-heres-a-variable-importance-chart-made-from-a-similar-data-set)? [The CSV in the repo](https://github.com/arielf/weight-loss/blob/master/ariel.csv) only has 120 days worth of data vs. a weight variation from 186.8lbs to 182.8, which over 4 months seems too insignificant to draw conclusions from.

Perhaps you've only shared a sample/excerpt of the data? Anyway, would be great if you could update the README on that point. Thanks!

**Comment by arielf** [comment]
@dandv 

First, thanks so much for the comment, the numbers and the links!

The toy data example is an example.  Unfortunately I don't have more data because at the time I stopped that particular experiment in 2012, the conclusions were clear enough to me and I found no need to collect more data and pursue the ML angle.  It took some more time for a wider set of learned experiences to sink in (seeing [Dr James McCarter talk on QS](https://vimeo.com/147795263) was another such high-impact event) and make me change my lifestyle.  Finally, the moment I started following strict LCHF with longer fasting periods and moderate exercise (over a year later), I started losing weight so fast, that maintaining a personal dataset on a daily basis seemed totally unnecessary.  That said, it would be great to get more data from others.

Observation: most ML practitioners and statisticians seem to view problems like this (and the associated data) as a batch machine learning problem with a clear conclusion (from some specific data-set) and some clear confidence margins. Essentially "a practical proof".

But real life tends to be different.  You don't decide to do an experiment one clear day, control M variables carefully, and get to a clear-cut conclusion N days later.  You try something, realize it doesn't work, try something else, etc. It is not a single experiment with data and a "proof", but rather [a contextual-bandit problem](https://en.wikipedia.org/wiki/Multi-armed_bandit): an exploration process mixed with random exploitation of discoveries.  A form of reinforcement learning.

So you should view the software+data included here is a subset of this reinforcement learning process.

Now, more to your specific point of statistical significance: note that the most recent version of the software no longer uses each day (about 120 days) as a single data point, it uses a variable-length sliding window on 1..N days over the data to increase sample size for the learning process significantly.  In addition, it uses a randomized bootstrapping on each data example (of 1 to N days) to add another multiplier towards reducing random noise and variance.

You may play with the `Makefile` `NDAYS` (max length in days of the sliding window) and `BS` (bootstrap multiplier) parameters to see how much results change, and which part remains relatively stable.  I did that and the conclusions were that indeed, items in the middle fall into the "too little data to conclude from" category. OTOH: items closer to the top/bottom, as a group, say pretty clearly that sleeping (fasting) longer and substituting carbs for fat, caused me to lose weight.

I will update the README and Q&A accordingly.

**Comment by arielf** [comment]
- Updated  `README.md` (original had a mistake in number of days: it is not "about 40 days", but "about 120 days").
- Also, expanded on sample-size and mitigation techniques in `QandA.md`
