### ISSUE TITLE
What does "nosleep" exactly mean?

### ISSUE THREAD

**Issue by blueblued** [arielf/weight-loss#28]
What does "nosleep" exactly mean?
Haven't you slept in all continuous 24 hours?

And, how about record the sleep data in this pattern: "sleep:6.5" (sleep[:hours]) ?

Thank you!

**Comment by arielf** [comment]
I see it closed, but for the benefit of others, maybe better explain it here.

Short answer: as explained in [ariel.csv](https://github.com/arielf/weight-loss/blob/master/ariel.csv) `nosleep` means less than normal (in this example, 8 hours) of sleep, whereas `sleep` means more than normal.

Generally, when doing ML with vowpal wabbit, weights start at zero and end-up relative to 0. The label is weight-gain (positive number) vs the previous data example.  Factors that drive weight-gain are positively correlated with that label, and factors that drive weight-loss are negatively correlated with the label.   If I use only one feature `sleep:[hours_of_sleep]` it'll be end-up biased (centered at 8 hours) which may make the result very misleading. Worst case: if you suffer from chronic sleep shortage, and you gain weight, it'll appear as if you gain weight by sleeping.

Ideally, this "model vs the norm" principle should be applied to all features, I didn't do it that way because at the time I didn't fully grasp the importance of it, and because what I ate was too diverse to apply the principle to.

**Comment by blueblued** [comment]
Arielf, It's so kind to receive your reply for a closed issue. That makes me rethink it which I thought I had understood.

Now I appreciate it more than before. I have known every factors should be "relative".

So a better model maybe like that:
1、Record everything with absolute quantity, such as: 
      R1: sleep:6(hours), bread:2(slices)
      R2: sleep:7(hours), bread:3(slices)

2、Average it and rewrite it with relative quantity, such as:
      R1: sleep:-0.5, bread:-0.5
      R2: sleep:0.5, bread:0.5

3、Analysis

What do you think?

**Comment by arielf** [comment]
Yes. Thanks. I was thinking about it myself, and I think this is a better approach.
When I get time I plan to change the pre-processing code so it does average (or median) every factor globally first and then assign relative weights depending on their magnitude vs this (median/average) norm.
