### ISSUE TITLE
Ambiguity on Weight Quantity

### ISSUE THREAD

**Issue by vontell** [arielf/weight-loss#6]
I was wondering how one might deal with the differing type of quantities for items in the third column. For example, if I slept 8 hours and had 1 slice of pizza in a day, would it be best to put `sleep:8 pizza:0.125` for example, or `sleep pizza`, etc... Looking more for your personal input on how to make the most of these weights.

**Comment by arielf** [comment]
This is a really _excellent_ and key question so thanks for asking.
I bumped into exactly this question while trying to make progress.

I may not have the best solution, so I'm always open for better ideas.

My current experience tells me you should emphasize and aim for _relative_ factors and deltas.  If you normally sleep 8 hours, that's your normal steady state.  Keeping it at 8 hours shouldn't affect your weight.  But when you make any _change_ vs the norm, **and** you see an effect in the target feature, that's what matters.  That's how I came-up with the '_sleep_' (more than 8 hours) and '_nosleep_' (less than 8 hours) features.  Thinking about it, I should probably have done the same for all features, but that would have complicated the whole data entry and making the whole story much harder to explain.

As for the exact weights: _vw_ is pretty amazing in its ability to auto-normalize and compensate for scales, that's why features with tiny weights (and a target label effect) end up being the most important.  It is a bit counter intuitive, but try it and you'll immediately see it.

Anyway, once you get over the noise: have really accurate scales, stick to accurate routines (same hour weighting for example) and have many data-points, you should be able to start seeing the weak signals screaming at you.  I found it very empowering to see this.

**Comment by baransn** [comment]
related question: in `ariel.csv` you say this:

```
# To emphasize any factor, i.e. make it more important/pronounced,
# in the importance order you need to _decrease_ its weight.
#
# This is due to the "less quantity drives more effect" principle
# when calculating _importance_ (effect on the target feature).
#
# e.g, if you avoid carbs, and one day you eat just one
# slice of bread, say 0.5 of a normal portion, you could do:
#
#       bread:0.5
```

A clarifying question: let's say I normally eat 3 slices of bread and today I ate 7.  Would I mark it as:

bread:2.33

or

bread:0.43

**Comment by arielf** [comment]
Short answer: you should mark it as:  _bread:4_  (i.e. based on additive, and relative to normal quantity) (or _bread:7_ if your consistent scheme is relative to 0==None and your "unit" is "a slice")

The rationale goes like this:
Say you gained 0.1 lb - this is the effect.  The question is which of the inputs caused this gain.

The cause (input feature) is what you ate, but the item weights learned by ML are _per-unit_ weights effects on the output, and they are relative to each other.

If a tiny slice of bread makes you gain a lot of weight it means "bread" as an entity that increases weight, has a lot of importance (effect).  If you stuffed yourself with 10 slices, and the gain is the same, then each "unit of bread" is less important.

But as long as you're consistent in your weighting and marking you should be able to interpret the results correctly.

**Comment by vontell** [comment]
Thanks for the advice, that makes a lot more sense! 😃
